# Generated by Django 4.1.4 on 2023-01-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comms_user',
            old_name='assign_id',
            new_name='pri_id',
        ),
        migrations.AddField(
            model_name='comms_user',
            name='emp_role',
            field=models.CharField(db_column='emp_role', max_length=50, null=True, verbose_name='Emp_Role'),
        ),
        migrations.AlterField(
            model_name='comms_user',
            name='emp_name',
            field=models.CharField(db_column='emp_name', max_length=50, verbose_name='Emp_Name'),
        ),
    ]
