# Generated by Django 4.1.4 on 2023-01-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0002_rename_assign_id_comms_user_pri_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comms_user',
            name='emp_id',
        ),
    ]
