# Generated by Django 4.1.4 on 2023-01-02 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0003_remove_comms_user_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_action',
            fields=[
                ('pri_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_email', models.EmailField(blank=True, db_column='emp_email', max_length=100, null=True, verbose_name='Emp_Email')),
                ('service_name', models.CharField(db_column='service_name', max_length=50, verbose_name='Service_name')),
                ('Action', models.CharField(db_column='action', max_length=50, verbose_name='Action')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'service_action',
            },
        ),
    ]
