# Generated by Django 4.1.4 on 2023-01-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0005_server_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='comms_user',
            name='server_name',
            field=models.CharField(db_column='server_name', max_length=50, null=True, verbose_name='Server_name'),
        ),
    ]
