# Generated by Django 4.1.4 on 2023-01-30 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0006_comms_user_server_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_activity',
            fields=[
                ('pri_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_email', models.EmailField(blank=True, db_column='emp_email', max_length=100, null=True, verbose_name='Emp_Email')),
                ('service_name', models.CharField(db_column='service_name', max_length=50, null=True, verbose_name='Service_name')),
                ('Action', models.CharField(db_column='action', max_length=50, null=True, verbose_name='Action')),
                ('action_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('login_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('logout_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'service_action',
            },
        ),
        migrations.DeleteModel(
            name='Service_action',
        ),
    ]
