# Generated by Django 4.1.4 on 2023-01-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0007_log_activity_delete_service_action'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log_activity',
            table='log_activity',
        ),
    ]
