# Generated by Django 4.1.4 on 2023-01-30 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0011_rename_action_time_log_activity_action_track_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_activity',
            name='action_track_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 5, 31, 26, 365018, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log_activity',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 5, 31, 26, 365018, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log_activity',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 5, 31, 26, 365018, tzinfo=datetime.timezone.utc)),
        ),
    ]
