# Generated by Django 4.1.4 on 2023-01-30 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0012_alter_log_activity_action_track_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_activity',
            name='action_track_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='log_activity',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='log_activity',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
