# Generated by Django 4.1.4 on 2023-01-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0013_alter_log_activity_action_track_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_activity',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='log_activity',
            name='logout_time',
        ),
    ]
