# Generated by Django 4.1.4 on 2023-01-30 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0014_remove_log_activity_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_activity',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='log_activity',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
