# Generated by Django 4.1.4 on 2023-01-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0017_alter_log_activity_action_track_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_activity',
            name='action_track_time',
            field=models.CharField(blank=True, db_column='action_track_time', max_length=100, null=True, verbose_name='Action_Track_Time'),
        ),
    ]
