# Generated by Django 4.1.4 on 2023-01-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0018_alter_log_activity_action_track_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_activity',
            name='login_time',
            field=models.CharField(blank=True, db_column='login_time', max_length=100, null=True, verbose_name='Login_Time'),
        ),
        migrations.AlterField(
            model_name='log_activity',
            name='logout_time',
            field=models.CharField(blank=True, db_column='logout_time', max_length=100, null=True, verbose_name='Logout_Time'),
        ),
    ]
