# Generated by Django 4.1.4 on 2023-01-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0020_server_details_db_driver_server_details_db_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_details',
            name='db_port_num',
            field=models.BigIntegerField(db_column='db_port_num', null=True, verbose_name='Db_Port_num'),
        ),
    ]
